### ISSUE TITLE
Only clone master branch and last commit

### ISSUE THREAD

**Issue by ibab** [everware/dockerspawner#4]
Only cloning the last commit on the master branch should speed up cloning for large repos.

**Comment by betatim** [comment]
`git clone --depth=1 <url>`

Any reason not to do it?

Especially for the clone that we make just to get the Dockerfile this could be good. Maybe the github API offers a way to retrieve a single file from a repository.

**Comment by ibab** [comment]
Yes, like this:
```
https://raw.githubusercontent.com/everware/everware/master/Dockerfile
```

**Comment by ibab** [comment]
Don't see any problems with `--depth=1`.
