### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by betatim** [everware/dockerspawner#8]
I'd like to deprecate aka delete this repo. As far as I can tell we don't need any custom stuff in `dockerspawner` so everyone should use `jupyter/dockerspawner` instead.

There are a few commits in this repo which are "unique" to this repo so not deleting it right away. From my side it is fine to bin those commits. @ibab @anaderi ?

**Comment by ibab** [comment]
I agree!

**Comment by anaderi** [comment]
Let me have a look tonight..

**Comment by anaderi** [comment]
good to close. everything we have here is in everware/spawner.py

**Comment by betatim** [comment]
Bye bye repo!
